apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: artifactory-pro.yml
objects:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    generation: 2
    labels:
      app: artifactory-pro
    name: artifactory-pro
  spec:
    replicas: 1
    selector:
      app: artifactory-pro
      deploymentconfig: artifactory-pro
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftWebConsole
        creationTimestamp: null
        labels:
          app: artifactory-pro
          deploymentconfig: artifactory-pro
      spec:
        containers:
        - image: docker.bintray.io/jfrog/artifactory-pro:latest
          imagePullPolicy: Always
          name: artifactory-pro
          ports:
          - containerPort: 8081
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /artifactory_extra_conf
            name: artifactory-pro-1
          - mountPath: /var/opt/jfrog/artifactory
            name: artifactory-pro-2
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: artifactory-pro-1
        - emptyDir: {}
          name: artifactory-pro-2
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - artifactory-pro
        from:
          kind: ImageStreamTag
          name: artifactory-pro:latest
          namespace: cicd-workflow
        lastTriggeredImage: docker.bintray.io/jfrog/artifactory-pro:latest
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
