---
#- name: Get Jenkins crumb
#  uri:
#    user: "{{user_name}}"
#    password: "{{password}}"
#    force_basic_auth: yes
#    url: "http://{{jenkins_url}}/crumbIssuer/api/json"
#    return_content: yes
#  register: crumb_token
#  until: crumb_token.content.find('Please wait while Jenkins is getting ready') == -1
#  retries: 10
#  delay: 5

#- name: Set crumb token
#  set_fact:
#    #crumb: "{{ crumb_token.json.crumbRequestField }}={{ crumb_token.json.crumb }}"
#    crumb: "{{ crumb_token.json.crumb }}"

- name: Invoke Jenkins RPC
  uri:
      url: "http://{{jenkins_url}}{{JOB_URL}}/createItem?name={{job_name}}"
      method: POST
      body: "{{lookup('template','{{config_file_name}}')}}"

      headers:
         #Jenkins-Crumb: "c0b6c11a56fd05fccbec1c4dc04d0e73"
#         Jenkins-Crumb: "{{crumb}}"
         Content-Type: "application/xml"
      user: "{{user_name}}"
      password: "{{password}}"
      timeout: 60
      status_code: 200
      return_content: yes
      validate_certs: no
      force_basic_auth: yes
  register: rpcResponse
  ignore_errors: yes
